Repository cheongw0n/cheongwon, pull requests merged in 2025-05, with the labels that each got.

#55 [Feature] #54 운영 환경 세팅
  Dockerfile
  gradlew
  src/main/java/com/hufs_cheongwon/common/config/SecurityConfig.java
  src/main/java/com/hufs_cheongwon/common/config/SwaggerConfig.java
Labels: 📃Docs

#65 feat(board): board 삭제 api 구현 및 super권한 부여
  src/main/java/com/hufs_cheongwon/common/config/SecurityConfig.java
  src/main/java/com/hufs_cheongwon/repository/BoardRepository.java
  src/main/java/com/hufs_cheongwon/web/controller/BoardController.java
Labels: ✨Feature

#70 [#69]hotfix: 비밀번호 변경 페퍼 추가
  src/main/java/com/hufs_cheongwon/service/UsersService.java
Labels: 🐞Bug

#72 [Chore] workflow yml update
  .github/workflows/build-gradle.yml
  .github/workflows/docker-image.yml
  .github/workflows/ec2-deploy.yml
  src/main/java/com/hufs_cheongwon/common/security/JwtAuthorizationFilter.java
Labels: 📃Docs
