Repository cheongw0n/cheongwon, pull requests merged in 2025-03, with the labels that each got.

#3 [Feature] 기본 엔티티 작성 및 연관관계 매핑
  src/main/java/com/hufs_cheongwon/domain/Admin.java
  src/main/java/com/hufs_cheongwon/domain/Agreement.java
  src/main/java/com/hufs_cheongwon/domain/Category.java
  src/main/java/com/hufs_cheongwon/domain/Petition.java
  src/main/java/com/hufs_cheongwon/domain/PetitionStatus.java
  src/main/java/com/hufs_cheongwon/domain/Report.java
  src/main/java/com/hufs_cheongwon/domain/Response.java
  src/main/java/com/hufs_cheongwon/domain/Users.java
  src/main/resources/application.yml
Labels: ✨Feature

#7 Test/#6 reissue test
  src/main/java/com/hufs_cheongwon/common/security/SecurityConfig.java
  src/main/java/com/hufs_cheongwon/domain/RefreshToken.java
  src/main/java/com/hufs_cheongwon/repository/RefreshTokenRepository.java
  src/main/java/com/hufs_cheongwon/service/RefreshTokenService.java
  src/main/java/com/hufs_cheongwon/service/UsersService.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/error/ErrorStatus.java
  src/main/java/com/hufs_cheongwon/web/controller/AdminController.java
  src/main/java/com/hufs_cheongwon/web/controller/UserController.java
  src/test/java/com/hufs_cheongwon/AdminAuthenticationTest.java
  src/test/java/com/hufs_cheongwon/SecurityTest.java
  src/test/java/com/hufs_cheongwon/UserLoginTest.java
  src/test/java/com/hufs_cheongwon/UserServiceTest.java
Labels: ✅Test, 🔨Refactor

#9 [Feature] 청원 관련 api 구현
  src/main/java/com/hufs_cheongwon/common/security/CustomUserDetails.java
  src/main/java/com/hufs_cheongwon/common/security/CustomUserDetailsService.java
  src/main/java/com/hufs_cheongwon/common/security/JwtAdminLoginFilter.java
  src/main/java/com/hufs_cheongwon/common/security/JwtUserLoginFilter.java
  src/main/java/com/hufs_cheongwon/common/security/SecurityConfig.java
  src/main/java/com/hufs_cheongwon/domain/Petition.java
  src/main/java/com/hufs_cheongwon/domain/enums/Category.java
  src/main/java/com/hufs_cheongwon/domain/enums/PetitionStatus.java
  src/main/java/com/hufs_cheongwon/repository/AgreementRepository.java
  src/main/java/com/hufs_cheongwon/repository/PetitionRepository.java
  src/main/java/com/hufs_cheongwon/repository/ReportRepository.java
  src/main/java/com/hufs_cheongwon/service/PetitionService.java
  src/main/java/com/hufs_cheongwon/service/RefreshTokenService.java
  src/main/java/com/hufs_cheongwon/service/UsersService.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/StatusCode.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/error/ErrorStatus.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/success/SuccessStatus.java
  src/main/java/com/hufs_cheongwon/web/controller/AdminController.java
  src/main/java/com/hufs_cheongwon/web/controller/PetitionController.java
  src/main/java/com/hufs_cheongwon/web/controller/UserController.java
  src/main/java/com/hufs_cheongwon/web/dto/Sample.java
  src/main/java/com/hufs_cheongwon/web/dto/request/EmailCertifyRequest.java
  src/main/java/com/hufs_cheongwon/web/dto/request/EmailSendRequest.java
  src/main/java/com/hufs_cheongwon/web/dto/request/LoginRequest.java
  src/main/java/com/hufs_cheongwon/web/dto/request/PetitionCreateRequest.java
  src/main/java/com/hufs_cheongwon/web/dto/response/LoginResponse.java
  src/main/java/com/hufs_cheongwon/web/dto/response/SignupResponse.java
Labels: ✨Feature

#10 [Feature] #8 로그아웃 탈퇴
  src/main/java/com/hufs_cheongwon/common/security/JwtAdminLoginFilter.java
  src/main/java/com/hufs_cheongwon/common/security/JwtAuthorizationFilter.java
  src/main/java/com/hufs_cheongwon/common/security/JwtUserLoginFilter.java
  src/main/java/com/hufs_cheongwon/common/security/JwtUtil.java
  src/main/java/com/hufs_cheongwon/common/security/SecurityConfig.java
  src/main/java/com/hufs_cheongwon/domain/BlackList.java
  src/main/java/com/hufs_cheongwon/domain/RefreshToken.java
  src/main/java/com/hufs_cheongwon/repository/BlackListRepository.java
  src/main/java/com/hufs_cheongwon/repository/RefreshTokenRepository.java
  src/main/java/com/hufs_cheongwon/repository/UsersRepository.java
  src/main/java/com/hufs_cheongwon/service/TokenService.java
  src/main/java/com/hufs_cheongwon/service/UsersService.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/error/ErrorStatus.java
  src/main/java/com/hufs_cheongwon/web/controller/AdminController.java
  src/main/java/com/hufs_cheongwon/web/controller/UserController.java
Labels: ✨Feature

#12 [Feature] 청원 답변 관련 api 구현
  build.gradle
  src/main/java/com/hufs_cheongwon/common/config/SwaggerConfig.java
  src/main/java/com/hufs_cheongwon/common/security/JwtAuthorizationFilter.java
  src/main/java/com/hufs_cheongwon/common/security/SecurityConfig.java
  src/main/java/com/hufs_cheongwon/domain/Petition.java
  src/main/java/com/hufs_cheongwon/domain/Response.java
  src/main/java/com/hufs_cheongwon/repository/PetitionRepository.java
  src/main/java/com/hufs_cheongwon/repository/ResponseRepository.java
  src/main/java/com/hufs_cheongwon/service/ResponseService.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/success/SuccessStatus.java
  src/main/java/com/hufs_cheongwon/web/controller/AdminController.java
  src/main/java/com/hufs_cheongwon/web/controller/PetitionController.java
  src/main/java/com/hufs_cheongwon/web/controller/ResponseController.java
  src/main/java/com/hufs_cheongwon/web/controller/UserController.java
  src/main/java/com/hufs_cheongwon/web/dto/request/ResponseCreateRequest.java
  src/main/java/com/hufs_cheongwon/web/dto/response/AgreementResponse.java
  src/main/java/com/hufs_cheongwon/web/dto/response/AnswerResponse.java
  src/main/java/com/hufs_cheongwon/web/dto/response/PetitionResponse.java
  src/main/java/com/hufs_cheongwon/web/dto/response/ReportResponse.java
Labels: ✨Feature

#14 [Feature] #13 cors 설정
  src/main/java/com/hufs_cheongwon/common/config/SecurityConfig.java
  src/main/java/com/hufs_cheongwon/common/config/SwaggerConfig.java
Labels: ✨Feature

#17 [Refactor] 청원과 답변 응답에 id값과 날짜 추가
  .gitignore
  src/main/java/com/hufs_cheongwon/common/Constant.java
  src/main/java/com/hufs_cheongwon/service/ResponseService.java
  src/main/java/com/hufs_cheongwon/web/controller/PetitionController.java
  src/main/java/com/hufs_cheongwon/web/dto/response/AnswerResponse.java
  src/main/java/com/hufs_cheongwon/web/dto/response/PetitionResponse.java
Labels: 🔨Refactor

#18 [Refactor] 이메일 인증
  build.gradle
  src/main/java/com/hufs_cheongwon/common/Constant.java
  src/main/java/com/hufs_cheongwon/common/config/CacheConfig.java
  src/main/java/com/hufs_cheongwon/common/security/JwtAdminLoginFilter.java
  src/main/java/com/hufs_cheongwon/common/security/JwtUserLoginFilter.java
  src/main/java/com/hufs_cheongwon/common/security/JwtUtil.java
  src/main/java/com/hufs_cheongwon/domain/Link.java
  src/main/java/com/hufs_cheongwon/domain/Petition.java
  src/main/java/com/hufs_cheongwon/domain/Tag.java
  src/main/java/com/hufs_cheongwon/service/CacheService.java
  src/main/java/com/hufs_cheongwon/service/UsersService.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/error/ErrorStatus.java
  src/main/java/com/hufs_cheongwon/web/controller/AdminController.java
  src/main/java/com/hufs_cheongwon/web/controller/UserController.java
  src/main/java/com/hufs_cheongwon/web/dto/request/EmailCertifyRequest.java
  src/main/java/com/hufs_cheongwon/web/dto/request/LoginRequest.java
  src/main/java/com/hufs_cheongwon/web/dto/request/PetitionCreateRequest.java
  src/main/resources/templates/email-template.html
Labels: ✨Feature

#21 [Feature]: 청원 통계 반환 api 구현
  src/main/java/com/hufs_cheongwon/common/Constant.java
  src/main/java/com/hufs_cheongwon/repository/PetitionRepository.java
  src/main/java/com/hufs_cheongwon/service/PetitionStatService.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/success/SuccessStatus.java
  src/main/java/com/hufs_cheongwon/web/controller/PetitionController.java
  src/main/java/com/hufs_cheongwon/web/dto/response/PetitionStatsDto.java
Labels: ✨Feature

#23 [Refactor] 커스텀 에러 선언 및 적용
  src/main/java/com/hufs_cheongwon/common/exception/InvalidStateException.java
  src/main/java/com/hufs_cheongwon/common/exception/ResourceNotFoundException.java
  src/main/java/com/hufs_cheongwon/common/security/CustomAdminDetailsService.java
  src/main/java/com/hufs_cheongwon/common/security/CustomUserDetailsService.java
  src/main/java/com/hufs_cheongwon/common/security/JwtAdminLoginFilter.java
  src/main/java/com/hufs_cheongwon/common/security/JwtAuthorizationFilter.java
  src/main/java/com/hufs_cheongwon/common/security/JwtUserLoginFilter.java
  src/main/java/com/hufs_cheongwon/service/PetitionService.java
  src/main/java/com/hufs_cheongwon/service/ResponseService.java
  src/main/java/com/hufs_cheongwon/service/TokenService.java
  src/main/java/com/hufs_cheongwon/service/UsersService.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/StatusCode.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/error/ErrorStatus.java
  src/main/java/com/hufs_cheongwon/web/controller/UserController.java
Labels: 🔨Refactor

#24 [Feature] 게시판 api
  src/main/java/com/hufs_cheongwon/domain/Board.java
  src/main/java/com/hufs_cheongwon/domain/enums/BoardType.java
  src/main/java/com/hufs_cheongwon/repository/BoardRepository.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/StatusCode.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/error/ErrorStatus.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/success/SuccessStatus.java
  src/main/java/com/hufs_cheongwon/web/controller/BoardController.java
  src/main/java/com/hufs_cheongwon/web/dto/response/BoardResponse.java
Labels: ✨Feature

#26 [Feature] 청원에 링크 추가
  src/main/java/com/hufs_cheongwon/domain/Link.java
  src/main/java/com/hufs_cheongwon/domain/Petition.java
  src/main/java/com/hufs_cheongwon/domain/Tag.java
  src/main/java/com/hufs_cheongwon/repository/AgreementRepository.java
  src/main/java/com/hufs_cheongwon/service/PetitionService.java
  src/main/java/com/hufs_cheongwon/service/UsersService.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/success/SuccessStatus.java
  src/main/java/com/hufs_cheongwon/web/controller/PetitionController.java
  src/main/java/com/hufs_cheongwon/web/controller/UserController.java
  src/main/java/com/hufs_cheongwon/web/dto/request/PetitionCreateRequest.java
  src/main/java/com/hufs_cheongwon/web/dto/response/AgreementResponse.java
  src/main/java/com/hufs_cheongwon/web/dto/response/AnswerResponse.java
  src/main/java/com/hufs_cheongwon/web/dto/response/PetitionResponse.java
Labels: ✨Feature, 🔨Refactor

#28 [Refactor]: petition 응답 최신 순 정렬
  src/main/java/com/hufs_cheongwon/repository/PetitionRepository.java
  src/main/java/com/hufs_cheongwon/web/controller/PetitionController.java
Labels: 🔨Refactor

#34 [Refactor]청원-상태별-응답에-인기-순-정렬-추가
  src/main/java/com/hufs_cheongwon/repository/PetitionRepository.java
  src/main/java/com/hufs_cheongwon/web/controller/PetitionController.java
  src/main/java/com/hufs_cheongwon/web/dto/PetitionSortType.java
Labels: 🔨Refactor

#32 [Fix]나홀로-프론트-요청-사항-들어주기
  src/main/java/com/hufs_cheongwon/common/config/SecurityConfig.java
  src/main/java/com/hufs_cheongwon/common/config/SwaggerConfig.java
  src/main/java/com/hufs_cheongwon/common/security/JwtAdminLoginFilter.java
  src/main/java/com/hufs_cheongwon/common/security/JwtUserLoginFilter.java
  src/main/java/com/hufs_cheongwon/domain/Board.java
  src/main/java/com/hufs_cheongwon/domain/Response.java
  src/main/java/com/hufs_cheongwon/repository/ResponseRepository.java
  src/main/java/com/hufs_cheongwon/service/BoardService.java
  src/main/java/com/hufs_cheongwon/service/ResponseService.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/error/ErrorStatus.java
  src/main/java/com/hufs_cheongwon/web/controller/BoardController.java
  src/main/java/com/hufs_cheongwon/web/controller/PetitionController.java
  src/main/java/com/hufs_cheongwon/web/controller/ResponseController.java
  src/main/java/com/hufs_cheongwon/web/controller/UserController.java
  src/main/java/com/hufs_cheongwon/web/dto/request/BoardCreateRequest.java
  src/main/java/com/hufs_cheongwon/web/dto/request/BoardUpdateRequest.java
  src/main/java/com/hufs_cheongwon/web/dto/response/PetitionResponse.java
Labels: 🐞Bug, ✨Feature

#35 [Feature]: 매일 일정 기간이 지난 청원의 상태를 변경하는 스케줄러 구현
  src/main/java/com/hufs_cheongwon/HufsCheongwonApplication.java
  src/main/java/com/hufs_cheongwon/common/Constant.java
  src/main/java/com/hufs_cheongwon/common/scheduler/PetitionStatusScheduler.java
  src/main/java/com/hufs_cheongwon/repository/PetitionRepository.java
Labels: ✨Feature

#36 [Feature] 어드민 청원 삭제
  src/main/java/com/hufs_cheongwon/common/config/SecurityConfig.java
  src/main/java/com/hufs_cheongwon/common/security/CustomAdminDetails.java
  src/main/java/com/hufs_cheongwon/common/security/JwtAdminLoginFilter.java
  src/main/java/com/hufs_cheongwon/common/security/JwtAuthorizationFilter.java
  src/main/java/com/hufs_cheongwon/domain/Petition.java
  src/main/java/com/hufs_cheongwon/domain/RefreshToken.java
  src/main/java/com/hufs_cheongwon/service/PetitionService.java
  src/main/java/com/hufs_cheongwon/service/ResponseService.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/success/SuccessStatus.java
  src/main/java/com/hufs_cheongwon/web/controller/AdminController.java
  src/main/java/com/hufs_cheongwon/web/controller/SuperAdminController.java
Labels: ✨Feature

#39 [Feature]/#38 비밀번호 찾기
  src/main/java/com/hufs_cheongwon/common/Util.java
  src/main/java/com/hufs_cheongwon/common/config/SecurityConfig.java
  src/main/java/com/hufs_cheongwon/common/security/CustomAdminDetailsService.java
  src/main/java/com/hufs_cheongwon/common/security/CustomUserDetailsService.java
  src/main/java/com/hufs_cheongwon/common/security/JwtAdminLoginFilter.java
  src/main/java/com/hufs_cheongwon/common/security/JwtAuthorizationFilter.java
  src/main/java/com/hufs_cheongwon/common/security/JwtUserLoginFilter.java
  src/main/java/com/hufs_cheongwon/domain/Petition.java
  src/main/java/com/hufs_cheongwon/domain/Users.java
  src/main/java/com/hufs_cheongwon/domain/enums/UsersStatus.java
  src/main/java/com/hufs_cheongwon/repository/PetitionRepository.java
  src/main/java/com/hufs_cheongwon/service/PetitionService.java
  src/main/java/com/hufs_cheongwon/service/ResponseService.java
  src/main/java/com/hufs_cheongwon/service/TokenService.java
  src/main/java/com/hufs_cheongwon/service/UsersService.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/error/ErrorStatus.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/success/SuccessStatus.java
  src/main/java/com/hufs_cheongwon/web/controller/UserController.java
  src/main/java/com/hufs_cheongwon/web/dto/response/AuthInfoResponse.java
  src/test/java/com/hufs_cheongwon/SecurityTest.java
Labels: ✨Feature

#41 [Refactor]: 에러 핸들러의 일부 메소드를 해당 에러의 메시지를 사용하도록 수정
  src/main/java/com/hufs_cheongwon/common/exception/GlobalExceptionHandler.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/error/ErrorResponse.java
Labels: 🔨Refactor

#45 [Refactor] 이메일 인증 폼 개선
  src/main/resources/templates/email-template.html
Labels: 🔨Refactor

#43 [Feature]: 청원 등록 시 7일간 등록 제한 기능 구현
  src/main/java/com/hufs_cheongwon/common/exception/BusinessException.java
  src/main/java/com/hufs_cheongwon/repository/PetitionRepository.java
  src/main/java/com/hufs_cheongwon/service/PetitionService.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/error/ErrorStatus.java
Labels: ✨Feature

#48 [Feature] 청원 북마크 기능
  src/main/java/com/hufs_cheongwon/common/config/SecurityConfig.java
  src/main/java/com/hufs_cheongwon/domain/Petition.java
  src/main/java/com/hufs_cheongwon/domain/PetitionBookmark.java
  src/main/java/com/hufs_cheongwon/domain/Users.java
  src/main/java/com/hufs_cheongwon/repository/PetitionBookmarkRepository.java
  src/main/java/com/hufs_cheongwon/service/PetitionService.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/success/SuccessStatus.java
  src/main/java/com/hufs_cheongwon/web/controller/PetitionController.java
  src/main/java/com/hufs_cheongwon/web/dto/response/PetitionBookmarkResponse.java
Labels: ✨Feature

#50 [Refactor] 사용자 탈퇴 리팩토링
  src/main/java/com/hufs_cheongwon/common/Constant.java
  src/main/java/com/hufs_cheongwon/common/Util.java
  src/main/java/com/hufs_cheongwon/common/config/SecurityConfig.java
  src/main/java/com/hufs_cheongwon/common/scheduler/UsersStatusScheduler.java
  src/main/java/com/hufs_cheongwon/common/security/CustomUserDetailsService.java
  src/main/java/com/hufs_cheongwon/common/security/JwtUserLoginFilter.java
  src/main/java/com/hufs_cheongwon/domain/Users.java
  src/main/java/com/hufs_cheongwon/repository/UsersRepository.java
  src/main/java/com/hufs_cheongwon/service/UsersService.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/error/ErrorStatus.java
  src/main/java/com/hufs_cheongwon/web/apiResponse/success/SuccessStatus.java
  src/main/java/com/hufs_cheongwon/web/controller/UserController.java
  src/main/java/com/hufs_cheongwon/web/dto/response/AnswerResponse.java
  src/main/java/com/hufs_cheongwon/web/dto/response/PetitionResponse.java
Labels: 🔨Refactor

#52 [#51] fix: 유저 테이블 칼럼 수정
  src/main/java/com/hufs_cheongwon/common/scheduler/UsersStatusScheduler.java
  src/main/java/com/hufs_cheongwon/common/security/CustomUserDetailsService.java
  src/main/java/com/hufs_cheongwon/domain/Users.java
  src/main/java/com/hufs_cheongwon/repository/UsersRepository.java
  src/main/java/com/hufs_cheongwon/service/UsersService.java
  src/test/java/com/hufs_cheongwon/SecurityTest.java
Labels: 🐞Bug
